feat(gate): deno worker should timeout internal functions to avoid infinite loop or similar (#375)
Attempt solving MET-120.

There seems to be an issue when using `setTimeout` and `setInterval` in
tests even if they are 'properly' cleared. (some might be cancelled
prematurely?)
```
Deno runtime ... should work with async function => ./typegate/tests/utils/test.ts:148:30
error: Leaking async ops:
  - 1 async operation to sleep for a duration was started before this test, but was completed during the test. Async operations should not complete in a test if they were not started in that test.
            This is often caused by not cancelling a `setTimeout` or `setInterval` call.
```

I also tried using an external sleep source like `$ sleep 1s` but it
seems to have similar issues
```
error: Leaking resources:
  - A child process stdout (rid 158) was opened before the test started, but was closed during the test. Do not close resources in a test that were not created during that test.
```

[Update]
Disable `sanitizeOps` while making sure all resources are closed
properly.
```typescript
Meta.test("test title", async (t) => {
  // test body
}, { sanitizeOps: false });
```

---------

Signed-off-by: Michaël <afmichael73@gmail.com>